"""
report_writer.py
----------------
Utility — Final Report Generator

Purpose : Format the outputs from all four agents into a clean,
          structured Markdown report and write it to disk.
Input   : All four agent output models + document metadata
Output  : Markdown file written to the outputs directory
"""

from pathlib import Path
from datetime import datetime

from src.agents.document_agent import DocumentOutput
from src.agents.summary_agent import SummaryOutput
from src.agents.retrieval_agent import RetrievalOutput
from src.agents.recommendation_agent import RecommendationOutput


def _format_list(items: list[str], empty_msg: str = "None identified.") -> str:
    """
    Format a list of strings as a Markdown bullet list.

    Args:
        items: List of string items.
        empty_msg: Message to show if the list is empty.

    Returns:
        Markdown-formatted bullet list string.
    """
    if not items:
        return f"- {empty_msg}"
    return "\n".join(f"- {item}" for item in items)


def generate_markdown_report(
    document_output: DocumentOutput,
    summary_output: SummaryOutput,
    retrieval_output: RetrievalOutput,
    recommendation_output: RecommendationOutput,
) -> str:
    """
    Assemble all agent outputs into a structured Markdown report.

    Args:
        document_output: Output from the Document Processing Agent.
        summary_output: Output from the Summary Agent.
        retrieval_output: Output from the RAG Retrieval Agent.
        recommendation_output: Output from the Recommendation Agent.

    Returns:
        Complete Markdown report as a string.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Format retrieved sources list
    sources_section = ""
    if retrieval_output.retrieved_chunks:
        seen_sources: set[str] = set()
        unique_sources = []
        for chunk in retrieval_output.retrieved_chunks:
            if chunk.source not in seen_sources:
                seen_sources.add(chunk.source)
                unique_sources.append(f"- **{chunk.title}** (`{chunk.source}`)")
        sources_section = "\n".join(unique_sources)
    else:
        sources_section = "- No relevant documents retrieved."

    # Format retrieved context excerpts (first 2 chunks for brevity)
    context_excerpts = ""
    for i, chunk in enumerate(retrieval_output.retrieved_chunks[:3], 1):
        excerpt = chunk.content[:400] + "..." if len(chunk.content) > 400 else chunk.content
        context_excerpts += f"\n### Excerpt {i} — {chunk.title}\n\n```\n{excerpt}\n```\n"

    report = f"""# Engineering Report Analysis

**Document:** `{document_output.document_name}`
**Pages:** {document_output.pages}
**Generated:** {timestamp}
**Model:** Gemini AI + RAG (FAISS + Sentence Transformers)

---

## Executive Summary

{summary_output.executive_summary}

---

## Key Findings

{_format_list(summary_output.key_findings)}

---

## Failed Tests

{_format_list(summary_output.failed_tests, "No failed tests identified.")}

---

## Identified Risks

{_format_list(summary_output.risks, "No explicit risks identified.")}

---

## Observations

{_format_list(summary_output.observations, "No additional observations.")}

---

## Retrieved Engineering Knowledge

**Query used for retrieval:**
> {retrieval_output.query[:300]}{"..." if len(retrieval_output.query) > 300 else ""}

**Sources consulted ({len(retrieval_output.retrieved_chunks)} chunk(s)):**
{sources_section}
{context_excerpts}

---

## Root Cause Analysis

{recommendation_output.root_cause}

---

## Recommended Next Actions

{_format_list(recommendation_output.next_actions)}

---

## Recommended Tests

{_format_list(recommendation_output.recommended_tests, "No additional tests recommended.")}

---

## Preventive Measures

{_format_list(recommendation_output.preventive_measures, "No preventive measures identified.")}

---

## Confidence Assessment

**Level:** {recommendation_output.confidence_level}

**Rationale:** {recommendation_output.confidence_rationale}

---

*Report generated by Engineering AI Workflow Assistant*
*Powered by LangGraph · Gemini · FAISS · Sentence Transformers*
"""
    return report


def save_report(
    report_content: str,
    output_path: Path,
) -> None:
    """
    Write the Markdown report to disk.

    Args:
        report_content: The complete Markdown report string.
        output_path: Full path where the report will be saved.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report_content, encoding="utf-8")
    print(f"\n[Report Writer] [OK] Report saved to: {output_path}")
